name: Check Images in Jupyter Notebook

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  check-images-in-notebook:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbformat jupyter notebook opencv-python pytest
        
    - name: Create check script
      run: |
        cat > check_images.py << 'EOL'
        import nbformat
        import re
        import os
        import sys


        required_images = ['Dr_Shashi_Tharoor.jpg', 'Plaksha_Faculty.jpg']


        # Load the notebook
        notebook_path = 'Lab 5-Spring 2025.ipynb'
        if not os.path.exists(notebook_path):
            print(f'Error: Notebook {notebook_path} not found')
            sys.exit(1)

        with open(notebook_path, 'r', encoding='utf-8') as f:
            notebook = nbformat.read(f, as_version=4)

        # Search for cv2.imread with our image files
        found_images = {img: False for img in required_images}
        cv2_import_found = False

        for cell in notebook.cells:
            if cell.cell_type == 'code':
                # Check for cv2 import
                if 'import cv2' in cell.source:
                    cv2_import_found = True
                    
                # Look for image loading with cv2.imread
                for img in required_images:
                    if f'cv2.imread' in cell.source and img in cell.source:
                        found_images[img] = True

        # Report results
        if not cv2_import_found:
            print('Warning: No import of cv2 found in notebook')
            
        not_found = [img for img, found in found_images.items() if not found]
        if not_found:
            print(f'Error: The following images are not loaded with cv2.imread in the notebook: {not_found}')
            sys.exit(1)
        else:
            print('Success: All required images are loaded with cv2.imread in the notebook')
        EOL

    - name: Run check script
      run: python check_images.py
      